name: usends
favicon: null
layout_spectrum: 0.43877
typography_spectrum: 0.77369
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3730972050689161
  lightness: 0.6848580907098949
  saturation: 0.2761737941764295
  rhythmicContrast: 0.6238566043321043
purpose: []
